<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <IsPackable>false</IsPackable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Mirko.Utility.Kafka" Version="1.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\VisitService.Shared\VisitService.Shared.csproj" />
	</ItemGroup>
</Project>
